POST http://localhost:7976/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query getHeader {
  getHeader {
    menu {
      links {
        title
        url
        external
      }
    }
  }
}
